# Generated by Django 3.0.4 on 2020-07-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailactivation',
            name='confrmable',
            field=models.BooleanField(default=True),
        ),
    ]
